### ISSUE TITLE
trying to send mail using the given code. 

### ISSUE THREAD

**Issue by vijaykarani333** [justinkalland/protonmail-api#68] opened 2021-05-23 03:45 UTC
node -v
v13.9.0

> typeof(ProtonMail(node:13204) UnhandledPromiseRejectionWarning: TimeoutError: waiting for selector "#ptSidebar" failed: timeout 30000ms eptceeded
    at new WaitTask (/Users/pt/code/node_modules/puppeteer/lib/DOMWorld.js:388:34)
    at DOMWorld._waitForSelectorOrptPath (/Users/pt/code/node_modules/puppeteer/lib/DOMWorld.js:313:26)
    at DOMWorld.waitForSelector (/Users/pt/code/node_modules/puppeteer/lib/DOMWorld.js:296:21)
    at Frame.waitForSelector (/Users/pt/code/node_modules/puppeteer/lib/FrameManager.js:384:51)
    at Frame.<anonymous> (/Users/pt/code/node_modules/puppeteer/lib/helper.js:95:27)
    at Page.waitForSelector (/Users/pt/code/node_modules/puppeteer/lib/Page.js:799:33)
    at ProtonMail._connect (/Users/pt/code/node_modules/protonmail-api/lib/proton-mail.js:59:16)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Function.connect (/Users/pt/code/node_modules/protonmail-api/lib/proton-mail.js:30:5)
    at async repl:2:14

**Comment by jim-fx** [comment] 2021-06-09 15:05
This error is caused by the new Protonmail redesign which changed the HTML. I just submitted a Pull Request  (#72). 

But as this Repo seems to be unmaintained I also published @jim-fx/protonmail-api which contains the fix.

Cheers, Jim

**Comment by jim-fx** [comment] 2021-06-10 18:10
No worries, thank you for the awesome work :)

**Comment by justinkalland** [comment] 2021-06-10 18:18
For transparency: I emailed @jim-fx and asked if he wanted to officially take over the project. If he agrees I will transfer it to him along with the NPM `protonmail-api`. I would like to see the project continuing living but don't have the bandwidth to maintain it.

**Comment by lTimeLordl** [comment] 2021-06-10 20:33
I suggest you to archive it and add a link in the README for an up to date fork.

**Comment by justinkalland** [comment] 2021-06-15 09:49
This has been fixed on version 2.1.1

**Comment by justinkalland** [comment] 2021-06-15 09:49
> I suggest you to archive it and add a link in the README for an up to date fork.

Decided for now to keep this project maintained as-is

**Closed by justinkalland** 2021-06-15 09:49 UTC
